from fastapi import FastAPI

app = FastAPI()

@app.get("/")
async def hello_world():
    return {"message": "Hello, World!"}


@app.get('/about')
async def about():
    return {"message": "This is the about page."}

# there is a cool feature in fastapi 
# if we run the server and go to /docs
# we will see the automatic interactive API documentation
# generated by Swagger UI